#!/bin/sh
echo "***********************************"
echo "*           OpenCockpit           *"
echo "*               by                *"
echo "*          xcentaurix             *"
echo "***********************************"
echo ""
echo "Plugin installed successfully."
echo "Please restart Enigma2 now!"
echo ""
exit 0
